jobs:
  mac:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
      with:
        submodules: true
    - continue-on-error: true
      uses: actions/setup-java@v3
      with:
        architecture: ${{ matrix.arch }}
        distribution: temurin
        java-version: '17'
    - continue-on-error: true
      name: Cache gradle deps
      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-${{ matrix.arch }}-gradle-${{ hashFiles('**/*.gradle*')
          }}
        path: ~/.gradle/caches
        restore-keys: '${{ runner.os }}-${{ matrix.arch }}-gradle

          '
    - continue-on-error: true
      name: Install dependencies
      run: 'brew install sass/sass/sass

        '
    - continue-on-error: true
      name: Update Version
      run: './gradlew updateVersion -PnewVersion=''${{  github.ref_name }}''

        '
    - continue-on-error: true
      if: matrix.arch == 'x64'
      name: Push Version Updates
      run: 'git config user.name ${{ github.actor }}

        git config user.email ${{ github.actor }}@users.noreply.github.com

        git add gradle.properties

        git commit -m "build: new version: ${{  github.ref_name }}"

        git push origin HEAD:main

        '
    - continue-on-error: true
      if: matrix.arch == 'x64'
      name: Package mac amd64
      run: ./gradlew packageMac -PpkgArch=amd64
    - continue-on-error: true
      if: matrix.arch == 'aarch64'
      name: Package mac arm64
      run: ./gradlew packageMac -PpkgArch=arm64
    - continue-on-error: true
      if: matrix.arch == 'x64'
      name: Generate changelog
      run: './gradlew genChangelog

        '
    - continue-on-error: true
      if: matrix.arch == 'x64'
      name: Generate upgrade package
      run: './gradlew geUpgradePackage

        '
    - continue-on-error: true
      if: matrix.arch == 'x64'
      name: Upload Upgrade Package
      uses: actions/upload-artifact@v3
      with:
        name: upgrade-package
        path: app/build/upgrade/*
    - continue-on-error: true
      name: Release macos
      uses: softprops/action-gh-release@v1
      with:
        files: 'app/build/packager/uncle-novel*.dmg

          app/build/packager/uncle-novel*.zip

          app/build/packager/uncle-novel*.pkg

          '
    - continue-on-error: true
      if: matrix.arch == 'x64'
      name: Release changelog
      uses: softprops/action-gh-release@v1
      with:
        body_path: ./changelog-latest.md
    strategy:
      matrix:
        arch:
        - x64
        - aarch64
  publish-upgrade:
    needs:
    - mac
    - win
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Clone upgrade repo
      uses: actions/checkout@v3
      with:
        path: upgrade
        repository: uncle-novel/upgrade
        token: ${{ secrets.P_TOKEN }}
    - continue-on-error: true
      name: Download upgrade package
      uses: actions/download-artifact@v3
      with:
        name: upgrade-package
        path: upgrade/novel/prod
    - continue-on-error: true
      name: Update upgrade package
      run: 'git config user.name github-actions[bot]

        git config user.email github-actions[bot]@users.noreply.github.com

        git add .

        git commit -m "Update upgrade package"

        git push origin HEAD:main'
      working-directory: upgrade
  win:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
      with:
        submodules: true
    - continue-on-error: true
      uses: actions/setup-java@v3
      with:
        architecture: ${{ matrix.arch }}
        distribution: temurin
        java-version: '17'
    - continue-on-error: true
      name: Init Exe4j License
      run: '${{ runner.workspace }}\uncle-novel\packager\exe4j9\bin\exe4jc.exe -L
        ${{ secrets.EXE4J_LICENSE }}

        '
      shell: cmd
    - continue-on-error: true
      name: Cache gradle deps
      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-${{ matrix.arch }}-gradle-${{ hashFiles('**/*.gradle*')
          }}
        path: '~/.gradle/caches

          '
        restore-keys: '${{ runner.os }}-${{ matrix.arch }}-gradle

          '
    - continue-on-error: true
      name: Install dependencies
      run: 'choco install sass

        choco install wixtoolset

        '
    - continue-on-error: true
      name: Update Version
      run: './gradlew updateVersion -PnewVersion=''${{  github.ref_name }}''

        '
    - continue-on-error: true
      if: matrix.arch == 'x64'
      name: Package windows x64
      run: ./gradlew packageWin64
    - continue-on-error: true
      if: matrix.arch == 'x86'
      name: Package windows x86
      run: ./gradlew packageWin32
    - continue-on-error: true
      name: Release windows
      uses: softprops/action-gh-release@v1
      with:
        files: 'app/build/packager/uncle-novel*.zip

          app/build/packager/uncle-novel*.exe

          '
    strategy:
      matrix:
        arch:
        - x64
        - x86
name: package
on:
  repository_dispatch:
    types: trigger-ga___release.yml
